services:
  mongo:
    platform: linux
    image: mongo:8
    ports:
      - "50002:27017"
#    volumes:
#      - nes_mongodata_linux_ci:/data/db
#      - nes_mongoconfig_linux_ci:/data/configdb

#volumes:
#  nes_mongodata_linux_ci:
#  nes_mongoconfig_linux_ci: