# Root Docker Compose file to run the tests on the development machine using some pre-initialized databases
# It must be used with powershell actions that mount the databases files.

version: '2.4' # 2.4 supports "platform", 3.x does not.

services:
  mongo:
    platform: linux
    image: mongo #@sha256:52c3314bee611f91d37b9b1bc0cc2755b1388f2de5b396b441f3fe94bef6c56c
    ports:
      - "50002:50002"
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "50002"]
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate() }" | mongosh --port 50002 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
#    volumes:
#      - nes_mongodata_linux_ci:/data/db
#      - nes_mongoconfig_linux_ci:/data/configdb

#volumes:
#  nes_mongodata_linux_ci:
#  nes_mongoconfig_linux_ci: