services:
  mongo:
    platform: windows
    image: mongo:8
    ports:
      - "50002:27017"
#    volumes:
#      - nes_mongodata_windows_ci:/data/db
#      - nes_mongoconfig_windows_ci:/data/configdb
#volumes:
#  nes_mongodata_windows_ci:
#  nes_mongoconfig_windows_ci: